#Rules for brave
windowrule =tags:3,appid:brave 
windowrule=focused_opacity:1,appid:brave

windowrule =tags:3,appid:helium 
windowrule=focused_opacity:1,appid:helium

windowrule=focused_opacity:0.95,appid:zen
windowrule =tags:3,appid:zen 


windowrule =tags:3,appid:firefox 
windowrule=focused_opacity:0.95,appid:firefox


#Rules for mpv
windowrule=tags:5,appid:mpv
windowrule=noblur:1,appid:mpv
windowrule=focused_opacity:1,appid:mpv
windowrule=isfloating:1,appid:mpv

# windowrule=focused_opacity:1,appid:Alacritty

#Rules for gtk-settings
windowrule=isfloating:1,appid:nwg-look

#Rules of eog
windowrule=focused_opacity:1,appid:org.gnome.eog
windowrule=isfloating:1,appid:org.gnome.eog

windowrule=focused_opacity:1,appid:zen

#satty
windowrule=isfloating:1,appid:com.gabm.satty

#nautilus
windowrule=isfloating:1,appid:pcmanfm

#Layer Rule for ROfi
layerrule=animation_type_open:zoom,noanim:0,noblur:0,layer_name:rofi

