
# sub config load
source=./mango-config/env.conf
source=./mango-config/animations.conf
source=./mango-config/bind.conf
source=./mango-config/rule.conf
source=./mango-config/tag.conf
source=./mango-config/cursor.conf
#exec-once =/home/sh4dow/.config/mango/autostart.sh
# startup
exec-once = noctalia





source=~/.config/mango/noctalia.conf

#source=./dms/cursor.conf
