# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x110f18ff
rootcolor = 0x15141bff
bordercolor = 0x6d6d6dff
dropcolor = 0xa277ff80
splitcolor = 0xffca85ff
focuscolor = 0xa277ffff
maximizescreencolor = 0x61ffcaff
urgentcolor = 0xff6767ff
scratchpadcolor = 0xffca85ff
globalcolor = 0x3e00c4ff
overlaycolor = 0x00ae73ff
jump_label_decorate_fg_color = 0xedeceeff
jump_label_decorate_bg_color = 0x322e48ff
jump_label_decorate_focus_fg_color = 0x15141bff
jump_label_decorate_focus_bg_color = 0xa277ffff
jump_label_decorate_border_color = 0x6d6d6dff
group_bar_decorate_fg_color = 0xedeceeff
group_bar_decorate_bg_color = 0x322e48ff
group_bar_decorate_focus_fg_color = 0x15141bff
group_bar_decorate_focus_bg_color = 0xa277ffff
group_bar_decorate_border_color = 0x6d6d6dff
