# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x0a0a12ff
bordercolor = 0x5b5c6dff
dropcolor = 0xbb353580
splitcolor = 0x9a7398ff
focuscolor = 0xbb3535ff
maximizescreencolor = 0x8baa82ff
urgentcolor = 0xc25b5bff
scratchpadcolor = 0x9a7398ff
globalcolor = 0x3e0e0eff
overlaycolor = 0x32502aff
jump_label_decorate_fg_color = 0xe4ded2ff
jump_label_decorate_bg_color = 0x1c1c2aff
jump_label_decorate_focus_fg_color = 0x191924ff
jump_label_decorate_focus_bg_color = 0xbb3535ff
jump_label_decorate_border_color = 0x5b5c6dff
group_bar_decorate_fg_color = 0xe4ded2ff
group_bar_decorate_bg_color = 0x1c1c2aff
group_bar_decorate_focus_fg_color = 0x191924ff
group_bar_decorate_focus_bg_color = 0xbb3535ff
group_bar_decorate_border_color = 0x5b5c6dff
